name = "pixdex-worker"
main = "src/index.ts"
compatibility_date = "2026-08-22"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "pixdex"
database_id = "f332865b-556c-4149-b4e4-a594ebc9334e"
migrations_dir = "migrations"

[[r2_buckets]]
binding = "THUMBNAILS"
bucket_name = "pixdex-thumbnails"
